### ISSUE TITLE
set_password doesn't use hash function

### ISSUE THREAD

**Issue by meilon** [kanthoney/knex-users#1]
Hi,

is it on purpose that the set_password function doesn't use the supplied hash function? I wondered why after changing the password the password_changed was successfully updated but login wasn't possible. Had to look into the database so see the plain password was used for updating the record.

Otherwise nice lib!

**Comment by kanthoney** [comment]
How did I miss that?  It should be fixed now.  Let me know if it's not.

**Comment by meilon** [comment]
Awesome, works for me, thanks for the fast fix.

But: I was coding away for some hours and didn't see the mail from GitHub and was wondering why my tests didn't work anymore on the CI server but still was green my machine. Gave up, checked the GitHub Inbox and saw this issue update. Would've been better to bump to `0.4.0` because `0.3.2` works for `~0.3.1`, the default setting for `npm install --save`. Had to remove my own fix, then it worked like a charm again.

Anyway, keep up the good work!
